/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import dao.Categoria1DAO;
import dao.CategoriaDAO;
import dao.ProductoDAO;
import dto.Categoria;
import dto.Producto;
import interfaces.InterfaceCategoria;
import interfaces.InterfaceProducto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gaby
 */
public class ProductoForm extends javax.swing.JInternalFrame {
     InterfaceCategoria ic = new Categoria1DAO();
InterfaceProducto ipa = new ProductoDAO();
DefaultTableModel dtm;
ArrayList<Categoria> lista1 = new ArrayList<>();    
ArrayList<Producto> lista2 = new ArrayList<>();
int idp = 0;
Producto p; 
    /**
     * Creates new form ProductoForm
     */
    public ProductoForm() {
        initComponents();
       cargarCombo();
       cargarTabla();
    }
  public final void cargarCombo(){
    lista1 = ic.listarCategoria();
    cbocategoria.addItem("Seleccionar Categoria");
    for(int i=0;i<lista1.size();i++){
    cbocategoria.addItem(lista1.get(i).getNomcat());
    }
  }
    public final void cargarTabla(){
 dtm = (DefaultTableModel) tblistas.getModel();
 lista2 = ipa.listarProducto();
 Object []datos = new Object[10];
 for(int i=0;i<lista2.size();i++){
     datos[0]=i+1;
     datos[1]=lista2.get(i).getIdprod();
     datos[2]=lista2.get(i).getIdcat();
     datos[3]=lista2.get(i).getNomprod();
     datos[4]=lista2.get(i).getColor();
    datos[5]=lista2.get(i).getMedida();
     datos[6]=lista2.get(i).getPeso();
     datos[7]=lista2.get(i).getStock();
     datos[8]=lista2.get(i).getEstado();
     datos[9]=lista2.get(i).getPrec_venta();
     
dtm.addRow(datos);
 }
tblistas.setModel(dtm);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbocategoria = new javax.swing.JComboBox();
        txtnombre = new javax.swing.JTextField();
        txtcolor = new javax.swing.JTextField();
        txtmedida = new javax.swing.JTextField();
        txtpeso = new javax.swing.JTextField();
        txtstock = new javax.swing.JTextField();
        txtestado = new javax.swing.JTextField();
        txtprec_vent = new javax.swing.JTextField();
        txtcat = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btncrear = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblistas = new javax.swing.JTable();

        jTextField2.setText("jTextField2");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Producto"));

        jLabel1.setText("Catgoria:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Color:");

        jLabel4.setText("Medida:");

        jLabel5.setText("Peso:");

        jLabel6.setText("Stock:");

        jLabel7.setText("Precio_Venta:");

        jLabel8.setText("Estado:");

        cbocategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbocategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbocategoria, 0, 205, Short.MAX_VALUE)
                    .addComponent(txtnombre)
                    .addComponent(txtcolor)
                    .addComponent(txtmedida)
                    .addComponent(txtpeso)
                    .addComponent(txtstock)
                    .addComponent(txtestado)
                    .addComponent(txtprec_vent))
                .addGap(30, 30, 30)
                .addComponent(txtcat, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbocategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(txtcat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtmedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtpeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtprec_vent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("OPERACIONES:"));

        btncrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add_to_shopping_basket.png"))); // NOI18N
        btncrear.setText("Crear");
        btncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearActionPerformed(evt);
            }
        });

        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/shopping_basket_accept.png"))); // NOI18N
        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/remove_from_shopping_basket.png"))); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/shopping_basket.png"))); // NOI18N
        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btncrear)
                        .addGap(18, 18, 18)
                        .addComponent(btneditar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btneliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnnuevo)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncrear)
                    .addComponent(btneditar))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btneliminar)
                    .addComponent(btnnuevo))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista Productos"));

        tblistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "idProducto", "idCategoria", "Nombre", "Color", "Medida", "Peso", "Stock", "Estado", "Precio_venta"
            }
        ));
        tblistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblistasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblistas);
        if (tblistas.getColumnModel().getColumnCount() > 0) {
            tblistas.getColumnModel().getColumn(0).setMaxWidth(50);
            tblistas.getColumnModel().getColumn(1).setMaxWidth(80);
            tblistas.getColumnModel().getColumn(2).setMaxWidth(80);
            tblistas.getColumnModel().getColumn(3).setMaxWidth(70);
            tblistas.getColumnModel().getColumn(4).setMaxWidth(70);
            tblistas.getColumnModel().getColumn(5).setMaxWidth(100);
            tblistas.getColumnModel().getColumn(6).setMaxWidth(80);
            tblistas.getColumnModel().getColumn(7).setMaxWidth(80);
            tblistas.getColumnModel().getColumn(8).setMaxWidth(80);
            tblistas.getColumnModel().getColumn(9).setMaxWidth(150);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbocategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbocategoriaActionPerformed
        // TODO add your handling code here:
       if(cbocategoria.getSelectedIndex()>0){
            txtcat.setText(""+ic.buscarIdCategoria(cbocategoria.getSelectedItem().toString()));
        }  
     
    }//GEN-LAST:event_cbocategoriaActionPerformed

    private void btncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearActionPerformed
        // TODO add your handling code here:
       int idcat,op,peso;
       String nomp,color, medida,stock,estado;
       double prevent;
        try {
           idcat = Integer.parseInt(txtcat.getText());
            nomp = txtnombre.getText();
            color = txtcolor.getText();
            medida = txtmedida.getText();
            stock = txtstock.getText();
            estado = txtestado.getText();
            prevent = Double.parseDouble(txtprec_vent.getText());
            peso = Integer.parseInt(txtpeso.getText());
            p = new Producto(idp, idcat, nomp, color, medida, peso, stock, estado, prevent);
            op = ipa.CrearProducto(p);
            limpiarComponentes();
            if(op==1){
                JOptionPane.showMessageDialog(null, "Registro Guardado");
                LimpiarJTable();
                cargarTabla();
            }else{
                JOptionPane.showMessageDialog(null, "Registro no Guardado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e+"HOLA");
        }
       
    }//GEN-LAST:event_btncrearActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
      if(tblistas.getSelectedRow()>=0){
            int fila = tblistas.getSelectedRow();
            int id = (int) tblistas.getValueAt(fila, 1);
            int op = ipa.EliminarProducto(id);
            if(op==1){
                JOptionPane.showMessageDialog(null, "Registro Eliminado");
                LimpiarJTable();
                cargarTabla();
            }else{
                JOptionPane.showMessageDialog(null, "Registro no Eliminado");
            }
        }else{
        JOptionPane.showMessageDialog(null, "Seleccionar Registro");
        }   
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // TODO add your handling code here:}
        int idcat,op,peso;
       String nomp,color, medida,stock,estado;
       double prevent;
         if(tblistas.getSelectedRow()>=0){
            idcat = Integer.parseInt(txtcat.getText());
            nomp = txtnombre.getText();
             color = txtcolor.getText();
            medida = txtmedida.getText();
            stock = txtstock.getText();
            estado = txtestado.getText();
            prevent = Double.parseDouble(txtprec_vent.getText());
            peso = Integer.parseInt(txtpeso.getText());
            p = new Producto(idp, idcat, nomp, color, medida, peso, stock, estado, prevent);
            op = ipa.EditarProducto(p);
            limpiarComponentes();
            if(op==1){
                JOptionPane.showMessageDialog(null, "Registro Modificado");
                LimpiarJTable();
                cargarTabla();
            }else{
                JOptionPane.showMessageDialog(null, "Registro no Modificado");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Seleccionar Registro");
        }
    }//GEN-LAST:event_btneditarActionPerformed

    private void tblistasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblistasMouseClicked
        // TODO add your handling code here:
       if(tblistas.getSelectedRow()>=0){
            int fila = tblistas.getSelectedRow();
            cbocategoria.setSelectedItem(ic.nomCategoria((int) tblistas.getValueAt(fila, 2)));
            txtnombre.setText((String) tblistas.getValueAt(fila, 3));
            txtcolor.setText((String) tblistas.getValueAt(fila, 4));
            txtmedida.setText((String) tblistas.getValueAt(fila, 5));
            txtpeso.setText( tblistas.getValueAt(fila, 6).toString());
            txtstock.setText((String) tblistas.getValueAt(fila, 7));
           txtestado.setText((String)tblistas.getValueAt(fila, 8));
            txtprec_vent.setText(tblistas.getValueAt(fila, 9).toString());
            idp = (int) tblistas.getValueAt(fila, 1);
        }else{
        }   
    }//GEN-LAST:event_tblistasMouseClicked

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
         limpiarComponentes();
    }//GEN-LAST:event_btnnuevoActionPerformed
  void limpiarComponentes(){
    cbocategoria.setSelectedIndex(0);
    txtnombre.setText(null);
    txtcolor.setText(null);
    txtmedida.setText(null);
    txtpeso.setText(null);
    txtstock.setText(null);
    txtestado.setText(null);
    txtprec_vent.setText(null);
}
   void LimpiarJTable(){
        int a = dtm.getRowCount()-1;  //Índices van de 0 a n-1
         for(int i=a;i>=0;i--){  
            dtm.removeRow(i);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncrear;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JComboBox cbocategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tblistas;
    private javax.swing.JTextField txtcat;
    private javax.swing.JTextField txtcolor;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtmedida;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtpeso;
    private javax.swing.JTextField txtprec_vent;
    private javax.swing.JTextField txtstock;
    // End of variables declaration//GEN-END:variables
}
